// <auto-generated />
using System;
using Alta_Flight.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alta_Flight.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Alta_Flight.Model.Account_Groups", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("accountID")
                        .HasColumnType("int");

                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("accountID");

                    b.HasIndex("group_id");

                    b.ToTable("Account_Group");
                });

            modelBuilder.Entity("Alta_Flight.Model.Accounts", b =>
                {
                    b.Property<int>("accountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("accountID"), 1L, 1);

                    b.Property<int?>("group_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phone")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("accountID");

                    b.HasIndex("role_id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Alta_Flight.Model.Groups", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("group_id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Group_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Member")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("Alta_Flight.Model.Roles", b =>
                {
                    b.Property<int>("role_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("role_id"), 1L, 1);

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Alta_Flight.Model.UpdateVersions", b =>
                {
                    b.Property<int>("Update_Version_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Update_Version_ID"), 1L, 1);

                    b.Property<string>("Update_Version_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("accountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Update_Version_ID");

                    b.HasIndex("accountID");

                    b.ToTable("UpdateVersion");
                });

            modelBuilder.Entity("Alta_Flight.Model.Account_Groups", b =>
                {
                    b.HasOne("Alta_Flight.Model.Accounts", "Account")
                        .WithMany("Account_Groups")
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Alta_Flight.Model.Groups", "Group")
                        .WithMany("Account_Groups")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Alta_Flight.Model.Accounts", b =>
                {
                    b.HasOne("Alta_Flight.Model.Roles", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Alta_Flight.Model.UpdateVersions", b =>
                {
                    b.HasOne("Alta_Flight.Model.Accounts", "Account")
                        .WithMany("UpdateVersions")
                        .HasForeignKey("accountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Alta_Flight.Model.Accounts", b =>
                {
                    b.Navigation("Account_Groups");

                    b.Navigation("UpdateVersions");
                });

            modelBuilder.Entity("Alta_Flight.Model.Groups", b =>
                {
                    b.Navigation("Account_Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
